// ===== API Configuration =====
export const API_URL = 'http://localhost:5000/api';

// ===== Hero Images (foto lokal Bandung) =====
export const HERO_VIDEOS = [
  '/Pangalengan1.mp4',
  '/tangkuban-perahu.mp4',
  '/kawah-putih.mp4',
];

// ===== Sample Queries untuk pencarian deskripsi =====
export const SAMPLE_QUERIES = [
  'wisata alam pegunungan sejuk',
  'tempat anak bermain wahana',
  'kuliner Sunda tradisional',
  'kebun teh dengan pemandangan',
  'air terjun jalur trekking',
  'museum edukasi anak',
];

// ===== Mapping Place_Id ke nama file foto lokal =====
export const PHOTO_MAP = {
  1: 'Alun-Alun Bandung.png',
  2: 'gedung sate.jpeg',
  3: 'jalan braga.jpg',
  4: 'Trans Studio Bandung.jpg',
  5: 'Saung Angklung Udjo.jpg',
  6: 'Museum Geologi.jpg',
  7: 'Museum Konferensi Asia Afrika.jpg',
  8: 'Taman Balai Kota.jpg',
  9: 'Taman Film.jpg',
  10: 'Taman Lansia.jpg',
  11: 'Taman Jomblo.jpg',
  12: 'Teras Cikapundung BBWS.jpg',
  13: 'Chinatown Bandung.jpg',
  14: 'Bandung Planning Gallery.jpg',
  15: 'Nu Art Studio.jpg',
  16: 'Amazing Artgames.jpg',
  17: 'Paris Van Java Resort Lifestyle Place.jpg',
  18: 'Paris Van Java Rooftop Garden.jpg',
  19: 'Cihampelas Walk.jpg',
  20: 'Skywalk Cihampelas.jpg',
  21: 'Pasar Baru Bandung.jpg',
  22: 'ITC Kebon Kalapa.jpg',
  23: 'Bandung Indah Plaza.jpg',
  24: '23 Paskal Shopping Center.jpg',
  25: 'Braga Citywalk.jpg',
  26: 'Festival Citylink.jpg',
  27: 'Kiara Artha Park.jpg',
  28: 'Babakan Siliwangi.jpg',
  29: 'Bandung Zoo.jpg',
  30: 'Karang Setra Waterpark.jpg',
  31: 'Lapangan Gasibu.jpg',
  32: 'Stadion Gelora Bandung Lautan Api.jpg',
  33: 'Taman Vanda.jpg',
  34: 'Taman Merdeka.jpg',
  35: 'Taman Citarum.jpg',
  36: 'Taman Veteran.jpg',
  37: 'Taman Sukajadi.jpg',
  38: 'Taman Antapani.jpg',
  39: 'Taman Arcamanik.jpg',
  40: 'Taman Gedebage.png',
  41: 'Taman Asia Afrika.jpg',
  42: 'Jalan Asia Afrika.jpg',
  43: 'Gedung Merdeka.jpg',
  44: 'Masjid Raya Bandung.jpg',
  45: 'Museum Sri Baduga.jpg',
  46: 'Museum Pos Indonesia.jpg',
  47: 'Museum Barli.jpg',
  48: 'Museum Nike Ardilla.jpg',
  49: 'Taman Musik Centrum.jpg',
  50: 'Taman Fotografi.jpg',
  51: 'Taman Sejarah.jpg',
  52: 'Taman Tegalega.jpg',
  53: 'Monumen Bandung Lautan Api.jpg',
  54: 'Gedung Indonesia Menggugat.jpg',
  55: 'Stadion Siliwangi.jpg',
  56: 'Masjid Al Jabbar.jpg',
  57: 'Alun-Alun Ujung Berung.jpg',
  58: 'Alun-Alun Cicendo.jpg',
  59: 'Pasar Cihapit.jpg',
  60: 'Pasar Kosambi.jpg',
  61: 'Pasar Andir.jpg',
  62: 'Cibadak Food Street.jpg',
  63: 'Paskal Hyper Square.jpg',
  64: 'Kuliner Night Asia Afrika.jpg',
  65: 'Sudirman Street Day and Night Market.jpg',
  66: 'Taman Saturnus.png',
  67: 'SPORT Jabar Arcamanik.jpg',
  68: 'GOR Arcamanik.jpg',
  69: 'GOR dan Taman Saparua.jpg',
  70: 'Museum Mandala Wangsit Siliwangi.jpg',
  71: 'Monumen Perjuangan Rakyat Jawa Barat.jpg',
  72: 'Gedung Isola.jpg',
  73: 'Penjara Banceuy Bandung.jpg',
  74: 'Kebun Binatang Bandung.jpg',
  75: 'Taman Sejarah Bandung.jpg',
  76: 'Masjid Salman ITB.jpg',
  77: 'Cibolang Hot Spring.jpg',
  78: 'Taman Lalu Lintas Ade Irma Suryani Nasution.jpg',
  79: 'Curug Dago.jpg',
  80: 'Plaza Cikapundung River Spot.jpg',
  81: 'Taman Pustaka Bunga.jpg',
  82: 'Taman Cikapayang Dago.jpg',
  83: 'Margacinta Park.jpg',
  84: 'Peta Park.jpg',
  85: 'Taman Braga.jpg',
  86: 'Snow Park at Panama Park.jpg',
  87: 'Bandros Bandung Tour on Bus.jpg',
  88: 'Alun-Alun Regol.jpg',
  89: 'Kampung Bamboo.jpg',
  90: 'SKY TREE Coffee and Eatery.jpg',
  91: 'Kampung Korea Bandung.jpg',
  92: 'Glamping Lakeside Rancabali.jpg',
  93: 'Gunung Puntang.jpg',
  94: 'Curug Cimahi.jpg',
  95: 'Curug Malela.jpg',
  96: 'Tebing Keraton.jpg',
  97: 'Situ Cileunca.jpg',
  98: 'Pemandian Air Panas Ciwidey.jpg',
  99: 'Barusen Hills.jpg',
  100: 'Skyline Best View Resto.jpg',
  101: 'Ranca Upas.jpg',
  102: 'Grafika Cikole.jpg',
  103: 'Farmhouse Lembang.jpg',
  104: 'Kawah Cibuni Rengganis.jpg',
  105: 'The Lodge Maribaya.jpg',
  106: 'Maribaya Hot Spring.jpg',
  107: 'Lembah Tengkorak Base Camp Via Bukit Tunggul.jpg',
  108: 'Dago Pakar.jpg',
  109: 'Taman Hutan Raya Djuanda.jpg',
  110: 'Goa Jepang.jpg',
  111: 'Goa Belanda.jpg',
  112: 'Situ Patengan.jpg',
  113: 'Stone Garden.jpg',
  114: 'Puncak Bintang.jpg',
  115: 'Bukit Moko.jpg',
  116: 'Wisata Batu Kuda.jpg',
  117: 'De Ranch Lembang.jpg',
  118: 'Lembang Park Zoo.jpg',
  119: 'Taman Begonia.jpg',
  120: 'Curug Omas.jpg',
  121: 'Curug Tilu.jpg',
  122: 'Curug Panganten.jpg',
  123: 'Bukit Cukul Pangalengan.jpg',
  124: 'Gunung Wayang.jpg',
  125: 'Gunung Windu.jpg',
  126: 'Situ Cisanti.jpg',
  127: 'Kampung Singkur.jpg',
  128: 'Sungai Palayangan.jpg',
  129: 'Kebun Teh Malabar.jpg',
  130: 'Situ Cangkuang.jpg',
  131: 'Kampung Naga.jpg',
  132: 'Curug Batu Templek.jpg',
  133: 'Curug Cinulang.jpg',
  134: 'Curug Halimun.jpg',
  135: 'Curug Siliwangi.jpg',
  136: 'Gunung Bukittunggul.jpg',
  137: 'Curug Cilengkrang.jpg',
  138: 'Curug Cipanji.jpg',
  139: 'Gunung Malabar.jpg',
  140: 'Situ Cipanunjang.jpg',
  141: 'Situ Cileunca Camping.jpg',
  142: 'Rafting Pangalengan Bandung.jpg',
  143: 'Teras Danoe Official camping Site.jpg',
  144: 'Tepi Sungai Resto Pasirjambu.jpg',
  145: 'Hulu Mata Air Sungai Cisangkuy.jpg',
  146: 'Bandungrafting Basecamp.jpg',
  147: 'Rafting ciwidey arung jeram.jpg',
  148: 'Bale Bambu Adventure Resort.jpg',
  149: 'Perkebunan Teh RANCABALI.jpg',
  150: 'Kebun Teh Pangalengan.jpg',
  151: 'Perkebunan Teh Purbasari.jpg',
  152: 'Sunrise Point Cukul.jpg',
  153: 'Bukit Indah Gambung.jpg',
  154: 'Bukit Jamur Rancabolang Pasirjambu.jpg',
  155: 'Dermaga Bintang.jpg',
  156: 'Bukit Moko Bandung.jpg',
  157: 'Taman Wisata Bougenville.jpg',
  158: 'Teras Bintang.jpg',
  159: 'Bukit Teletubbies Cicalengka.jpg',
  160: 'Kedaton Bukit Panyawangan Pangalengan.jpg',
  161: 'Taman Langit Pangalengan Sunrise Point and Camping Ground.jpg',
  162: 'Bukit Eon.jpg',
  163: 'Nuansa Riung gunung Pangalengan.jpg',
  164: 'Cukul Campsite.jpg',
  165: 'Puncak Sulibra artapela.jpg',
  166: 'Bukit Rahong.jpg',
  167: 'NIMO Highland.jpg',
  168: 'Cukul Atas.jpg',
  169: 'Kebun Teh Kertamanah.jpg',
  170: 'Situ Datar Buana.jpg',
  171: 'Situ Cileunca Pangalengan Bandung.jpg',
  172: 'Cileunca Land.jpg',
  173: 'Tepian Langit Girang. TLG.jpg',
  174: 'Wayang windu Panenjoan.jpg',
  175: 'Wayang Windu Village.jpg',
  176: 'Gunung Artapela.jpg',
  177: 'Kebun Teh Riung Gunung.jpg',
  178: 'Gunung Nini.jpg',
  179: 'Hutan Pinus Rahong.jpg',
  180: 'Padaawas Hills Pengalengan Bandung.jpg',
  181: 'Gravity Adventure.jpg',
  182: 'Lembah Pineus Rahong.jpg',
  183: 'Singkur Village.jpg',
  184: 'Green Corner Camping Pangalengan.jpg',
  185: 'Kiara Manuk.jpg',
  186: 'Alam Singkur.jpg',
  187: 'Pesona padaawas.jpg',
  188: 'Taman hutan Pinus Wayang Windu.jpg',
  189: 'Batu Pineus Riverside.jpg',
  190: 'Kawah Wayang.jpg',
  191: 'Pemandian Air Panas Cibolang.jpg',
  192: 'Teh Jangkung Malabar.jpg',
  193: 'Cabinite Pangalengan.jpg',
  194: 'Tea Plantation Observation Tower.jpg',
  195: 'Kampung Adat Cikondang.jpg',
  196: 'Makam Karomah Mahmud.jpg',
  197: 'Kampung Adat Cirendeu.jpg',
  198: 'Desa Wisata Tarumajaya.jpg',
  199: 'Cicalengka Dreamland.jpg',
  200: 'Kawah Putih.jpg',
  201: 'Penangkaran Rusa Ranca Upas.jpg',
  202: 'Desa Wisata Alamendah.jpg',
  203: 'Warnasari Campvan.jpg',
  204: 'Curug Batu Templek Cisanggarung.jpg',
  205: 'Curug Bentang Padjadjaran.jpg',
  206: 'Waduk Cirata.jpg',
  207: 'Bukit senyum.jpg',
  208: 'Taman Kupu-Kupu Cihanjuang.jpg',
  209: 'Sapulidi Cafe, Resort and Gallery.jpg',
  210: 'Tafso Barn.jpg',
  211: 'Lereng Anteng, Dago Bakery.jpg',
  212: 'The Great Asia Africa.jpg',
  213: 'Bird Pavilion.jpg',
  214: 'Ciwangun Indah Camp.jpg',
  215: 'Lembah Bougenville Resort.jpg',
  216: 'Warung Liwet Ibu Yayah.jpg',
  217: 'Bosscha.jpg',
  218: 'Fairy Garden Edutainment Park by The Lodge.jpg',
  219: 'LEMBANG Wonderland.jpg',
  220: 'MiniMania Lembang.jpg',
  221: 'Trizara Resorts Glamping Lembang.jpg',
  222: 'Pine Forest Camp.jpg',
  223: 'Orchid Forest Cikole.jpg',
  224: 'Gunung Putri Lembang.jpg',
  225: 'Wana Wisata Jayagiri.jpg',
  226: 'Curug Layung and Camping Ground.jpg',
  227: 'Gunung Burangrang.jpg',
  228: 'Gunung Hawu.jpg',
  229: 'Curug Tilu Leuwi Opat.jpg',
  230: 'Curug Pelangi.jpg',
  231: 'Guha Pawon.jpg',
  232: 'Lawangwangi Creative Space.jpg',
  233: 'Dago Bakery punclut.jpg',
  234: 'Kawasan Punclut.jpg',
  235: 'Waduk Saguling.jpg',
  236: 'MARIBAYA Natural Hotspring Resort.jpg',
  237: 'Terminal Wisata Grafika Cikole.jpg',
  238: 'Curug Bugbrug.jpg',
  239: 'Curug Sawer Cililin.jpg',
  240: 'Gn. Masigit.jpg',
  241: 'Basecamp Burangrang Via Legok Haji.jpg',
  242: 'Curug Maribaya.jpg',
  243: 'Farm House Susu Lembang.jpg',
  244: 'Kota Mini Lembang.jpg',
  245: 'Float Market Lembang, West Bandung, West Java.jpg',
  246: 'Dusun Bambu Lembang.jpg',
  247: 'Green Grass Cikole.jpg',
  248: 'Pine Valley Cikole.jpg',
  249: 'Team Merpati Gunung Putri.jpg',
  250: 'Tugu Bukit Tunggul.jpg',
  251: 'Bumi Perkemahan Taman Bincarung Pasir Angling.jpg',
  252: 'Rainbow Garden Lembang.jpg',
  253: 'Kebun Begonia Lembang.jpg',
  254: 'Kampung Daun Culture Gallery and Cafe.jpg',
  255: 'Dago Dreampark.jpg',
  256: 'Tebing Karaton.jpg',
  257: 'Sanghyang Heuleut.jpg',
  258: 'Taman Lembah DEWATA.jpg',
  259: 'Jendela Alam.jpg',
  260: 'Bukit Strawberry Berbunga.jpg',
  261: 'La Fresa Farm Wisata Petik Strawberry.jpg',
  262: 'Cikole Jayagiri Resort.jpg',
  263: 'Tebing Citatah 125.jpg',
  264: 'Pemandian Air Panas Nagrak Tengah.jpg',
  265: 'Pemandian Air Panas Cipanas.jpg',
  266: 'Sanghyang Kenit.jpg',
  267: 'Floating Market Lembang.jpg',
  268: 'Curug Cipanas.jpg',
  269: 'Curug Aseupan.jpg',
  270: 'Air Terjun Marbella.jpg',
  271: 'Stone Garden Citatah.jpg',
  272: 'Foresto Jayagiri Lembang.jpg',
  273: 'Benteng Jayagiri.jpg',
  274: 'Lorong Lumut.jpg',
  275: 'Tangkal Pinus Jayagiri Lembang.jpg',
  276: 'Jungle Milk Jayagiri.jpg',
  277: 'Talaga Land.jpg',
  278: 'Water Coaster - Dusun Bambu.jpg',
  279: 'Kamanja Adventure Land.jpg',
  280: 'Noahs Park.jpg',
  281: 'Kampung Gajah Park and Zoo.jpg',
  282: 'Vila Air Natural Resort.jpg',
  283: 'Sendang Geulis Kahuripan.jpg',
  284: 'Situ Ciburuy.jpg',
  285: 'Sanghyang Tikoro.jpg',
  286: 'Lembang Park Zoo.jpg',
  287: 'Gunung Tangkuban Perahu.jpg',
  288: 'Sanghyang Poek Bandung purba.jpg',
  289: 'Taman Maluku.jpg',
  290: 'Taman Pramuka.jpg',
  291: 'Taman Cibeunying.jpg',
  292: 'Taman Cilaki.jpg',
  293: 'Taman Centrum.jpg',
  294: 'Taman Dewi Sartika.jpg',
  295: 'Museum Pendidikan Nasional.jpg',
  296: 'Museum Kota Bandung.jpg',
  297: 'Museum NuArt Sculpture Park.jpg',
  298: 'Selasar Sunaryo Art Space.jpg',
  299: 'Museum Asia Afrika.jpg',
  300: 'Vihara Dharma Ramsi.jpg',
  301: 'Gereja Katedral Bandung.jpg',
  302: 'Pasar Cikapundung.jpg',
  303: 'Pasar Gedebage.jpg',
  304: 'Trans Studio Mall Bandung.jpg',
  305: 'Miko Mall.jpg',
  306: 'Bandung Electronic Center.jpg',
  307: 'Istana Plaza.jpg',
  308: 'Metro Indah Mall.jpg',
  309: 'Punclut.jpg',
  310: 'Caringin Tilu.jpg',
  311: 'Dago Tea House.jpg',
  312: 'Saung Udjo Heritage.jpg',
  313: 'Rumah Mode Factory Outlet.jpg',
  314: 'Heritage Factory Outlet.jpg',
  315: 'Stamp Festival Bandung.jpg',
  316: 'Cibaduyut.jpg',
  317: 'Sentra Rajut Binong Jati.jpg',
  318: 'Sentra Boneka Sukamulya.jpg',
  319: 'Kawah Putih Ciwidey.jpg',
  320: 'Kebun Strawberry Ciwidey.jpg',
  321: 'Pemandian Air Panas Cimanggu.jpg',
  322: 'Pemandian Air Panas Walini.jpg',
  323: 'Kawah Cibuni.jpg',
  324: 'Makam Bosscha Pangalengan.jpg',
  325: 'Curug Sindulang.jpg',
  326: 'Curug Citambur.jpg',
  327: 'Gunung Patuha.jpg',
  328: 'Bukit Jamur Rancaupas.jpg',
  329: 'Pinus Rahong Cikondang.jpg',
  330: 'Glamping Legok Kondang.jpg',
  331: 'Kampung Mahmud.jpg',
  332: 'Masjid Attaawun Puncak.jpg',
  333: 'Wisata Religi Cibiru.jpg',
  334: 'Wisata Sungai Cikapundung Maribaya.jpg',
  335: 'Outbound Cikole.jpg',
  336: 'Paintball Lembang.jpg',
  337: 'Trizara Resorts.jpg',
  338: 'Dusun Bambu Family Leisure Park.jpg',
  339: 'Farmhouse Susu Lembang.jpg',
  340: 'Kampung Gajah Wonderland.jpg',
  341: 'Sari Ater Hot Spring.jpg',
  342: 'Curug Layung.jpg',
  343: 'Curug Omas Maribaya.jpg',
  344: 'Stone Garden Padalarang.jpg',
  345: 'Gunung Batu Lembang.jpg',
  346: 'Observatorium Bosscha.jpg',
  347: 'Bandung Treetop Adventure Park.jpg',
  348: 'Punclut Bandung Barat.jpg',
  349: 'Lereng Anteng.jpg',
  350: 'Sapu Lidi Resort.jpg',
  351: 'Imah Seniman.jpg',
  352: 'Bumi Sangkuriang.jpg',
  353: 'Sindang Reret Cikole.jpg',
  354: 'DDieuland Bandung.jpg',
  355: 'Wot Batu.jpg',
  356: 'Boscha Junior Hill Park.jpg',
  357: 'Pulosari Adventure.jpg',
  358: 'Saung Daweung Resort.jpg',
  359: 'Sanghyang Poek.jpg',
  360: 'Bumi Perkemahan Cikole.jpg',
  361: 'Kampung Cai Ranca Upas.jpg',
};

// ===== Foto fallback per kategori (dari Unsplash) =====
const FALLBACK_BY_CATEGORY = {
  'Wisata Alam': '1501785888041-af3ef285b470',
  'Taman Hiburan': '1535082623926-b39352a03fb7',
  'Taman Kota': '1519331379826-f10be5486c6f',
  'Wisata Kuliner': '1414235077428-338989a2e8c0',
  'Pusat Perbelanjaan': '1567958451986-2de427a4a0be',
  'Wisata Edukasi': '1606761568499-6d2451b23c66',
  'Wisata Sejarah': '1577720580479-7d839d829c73',
  'Wisata Olahraga': '1517649763962-0c623066013b',
  'Museum': '1565060169187-5284a3bb2444',
  'Wisata Budaya': '1583224964978-2257b960c3d3',
  'Wisata Religi': '1542376333-6e1d2c0d5a99',
  'Wisata Seni': '1536924940846-227afb31e2a5',
  'Desa Wisata': '1604334669924-c0e3f5b06abe',
};

// ===== Fungsi utama: ambil URL foto destinasi =====
export const getDestinationImage = (placeName, category, placeId = null) => {
  if (placeId && PHOTO_MAP[placeId]) {
    // Nama file sudah aman (tanpa karakter spesial), cuma encode spasi
    const safeFilename = PHOTO_MAP[placeId].replace(/ /g, '%20');
    return `/images/destinations/${safeFilename}`;
  }
  const fallback = FALLBACK_BY_CATEGORY[category] || FALLBACK_BY_CATEGORY['Wisata Alam'];
  return `https://images.unsplash.com/photo-${fallback}?w=900&q=85`;
};

// ===== Reusable Icons =====
export const Icons = {
  pin: (size = 14) => (
    <svg width={size} height={size} viewBox="0 0 14 14" fill="none">
      <path d="M7 1.2 C4.5 1.2 2.5 3.2 2.5 5.7 C2.5 9 7 12.8 7 12.8 C7 12.8 11.5 9 11.5 5.7 C11.5 3.2 9.5 1.2 7 1.2 Z" stroke="currentColor" strokeWidth="1.3" fill="none"/>
      <circle cx="7" cy="5.7" r="1.7" stroke="currentColor" strokeWidth="1.3" fill="none"/>
    </svg>
  ),
  arrow: (size = 14) => (
    <svg width={size} height={size} viewBox="0 0 14 14" fill="none">
      <path d="M3 7 H11 M7.5 3.5 L11 7 L7.5 10.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  ),
  sparkle: (size = 14) => (
    <svg width={size} height={size} viewBox="0 0 14 14" fill="none">
      <path d="M7 1 L8 5 L12 6 L8 7 L7 11 L6 7 L2 6 L6 5 Z" fill="currentColor"/>
    </svg>
  ),
};
